import { useEffect, useState } from "react";
import { db, collection, doc, updateDoc, onSnapshot } from "./firebase.js";
export default function Admin({ crew }) {
  const [members,setMembers]=useState([]),[meetups,setMeetups]=useState([]),[reviews,setReviews]=useState([]);
  useEffect(()=>{if(!crew)return; const u1=onSnapshot(collection(db,"members"),s=>setMembers(s.docs.map(d=>({id:d.id,...d.data()})))); const u2=onSnapshot(collection(db,"meetups"),s=>setMeetups(s.docs.map(d=>({id:d.id,...d.data()})))); const u3=onSnapshot(collection(db,"reviews"),s=>setReviews(s.docs.map(d=>({id:d.id,...d.data()})))); return()=>{u1();u2();u3();}},[crew]);
  if(!crew) return <main className="page narrow"><section className="card center"><h1>크루 전용</h1><p className="muted">상단의 크루 버튼으로 로그인해 주세요.</p></section></main>;
  const pendingMembers=members.filter(m=>m.status==="pending"), pendingMeetups=meetups.filter(m=>m.status==="pending");
  const approveMember=id=>updateDoc(doc(db,"members",id),{status:"approved"}), rejectMember=id=>updateDoc(doc(db,"members",id),{status:"rejected"}); const approveMeetup=id=>updateDoc(doc(db,"meetups",id),{status:"approved"}), rejectMeetup=id=>updateDoc(doc(db,"meetups",id),{status:"rejected"});
  const csv=()=>{const rows=[["이름","성별","생년월일","사는 곳","직장 위치","연락처","상태"],...members.map(m=>[m.name,m.gender,m.birthdate,m.homeArea,m.workArea,m.phone,m.status])]; const text="\\ufeff"+rows.map(r=>r.map(v=>`"${String(v||"").replace(/"/g,'""')}"`).join(",")).join("\\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type:"text/csv"})); a.download="pado_members.csv"; a.click();};
  return <main className="page"><div className="sectionTitle"><div><p className="eyebrow">CREW DASHBOARD</p><h1>크루 대시보드</h1></div><button className="btn" onClick={csv}>CSV 다운로드</button></div><section className="dash"><article><span>회원 승인 대기</span><b>{pendingMembers.length}</b></article><article><span>밋업 승인 대기</span><b>{pendingMeetups.length}</b></article><article><span>전체 후기</span><b>{reviews.length}</b></article><article><span>전체 밋업</span><b>{meetups.length}</b></article></section><section className="grid two"><article className="card"><h2>가입 승인 대기</h2><div className="list">{pendingMembers.length?pendingMembers.map(m=><div className="item" key={m.id}><h3>{m.name}</h3><p className="meta">{m.gender} · {m.birthdate}<br/>🏠 {m.homeArea}<br/>💼 {m.workArea||"미입력"}<br/>☎️ {m.phone}<br/>📷 {m.instagram||"미입력"}</p><p>{m.note}</p><button className="btn success" onClick={()=>approveMember(m.id)}>승인</button> <button className="btn danger" onClick={()=>rejectMember(m.id)}>반려</button></div>):<p className="muted">승인 대기 회원이 없어요.</p>}</div></article><article className="card"><h2>밋업 승인 대기</h2><div className="list">{pendingMeetups.length?pendingMeetups.map(m=><div className="item" key={m.id}><h3>{m.title}</h3><p className="meta">{m.date} {m.time}<br/>📍 {m.location}<br/>밋업장: {m.host}</p><p>{m.desc}</p><button className="btn success" onClick={()=>approveMeetup(m.id)}>승인</button> <button className="btn danger" onClick={()=>rejectMeetup(m.id)}>반려</button></div>):<p className="muted">승인 대기 밋업이 없어요.</p>}</div></article></section></main>;}