import{useEffect,useMemo,useState}from"react";
import{db,collection,onSnapshot,addDoc,serverTimestamp}from"./firebase.js";
const pad=n=>String(n).padStart(2,"0");const fmt=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const lightningTopics=["퇴근 후 저녁 먹으실 분?","코노 가서 한 곡 부르실 분?","책 읽고 카페 가실 분?","가볍게 산책하실 분?","맛집 뿌수러 가실 분?","영화 보실 분?","브런치&카페 가실 분?"];
const lightningPlaces=["서면 · 전포 일대","광안리","해운대","동래 · 온천장","부산대","남포동"];
export default function Home({go,approved}){const[meetups,setMeetups]=useState([]),[reviews,setReviews]=useState([]),[members,setMembers]=useState([]),[notices,setNotices]=useState([]);useEffect(()=>{const u1=onSnapshot(collection(db,"meetups"),s=>setMeetups(s.docs.map(d=>({id:d.id,...d.data()}))));const u2=onSnapshot(collection(db,"reviews"),s=>setReviews(s.docs.map(d=>({id:d.id,...d.data()}))));const u3=onSnapshot(collection(db,"members"),s=>setMembers(s.docs.map(d=>({id:d.id,...d.data()}))));const u4=onSnapshot(collection(db,"notices"),s=>setNotices(s.docs.map(d=>({id:d.id,...d.data()}))));return()=>{u1();u2();u3();u4()}},[]);
useEffect(()=>{const now=new Date();if(now.getHours()<9)return;const today=fmt(now);if(meetups.some(m=>m.isDailyLightning&&m.date===today))return;const seed=now.getDate()+now.getMonth()*3;addDoc(collection(db,"meetups"),{title:lightningTopics[seed%lightningTopics.length],date:today,time:"19:30",location:lightningPlaces[seed%lightningPlaces.length],host:"파도 크루",min:3,max:8,cost:"각자 계산",desc:"매일 오전 9시에 자동으로 열리는 오늘의 번개예요. 3명이 모이면 정식 밋업으로 전환됩니다.",kakao:"",generation:1,isLightning:true,isDailyLightning:true,participants:[],waitlist:[],status:"approved",createdAt:serverTimestamp()}).catch(()=>{});},[meetups]);
const approvedMeetups=meetups.filter(m=>m.status==="approved");const today=fmt(new Date());const todayLightning=approvedMeetups.find(m=>m.isLightning&&m.date===today)||approvedMeetups.find(m=>m.isLightning)||approvedMeetups[0];const week=useMemo(()=>{const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),end=new Date(start);end.setDate(start.getDate()+7);return approvedMeetups.filter(m=>{const d=new Date((m.date||"")+"T00:00:00");return d>=start&&d<=end}).slice(0,6)},[meetups]);
const openCreate=()=>{if(!approved){go("signup");return}sessionStorage.setItem("padoOpenCreate","1");go("meetups")};
const openToday=()=>{sessionStorage.setItem("padoMeetupView","today");go("meetups")};
const defaultNotices=[
{id:"score",title:"활동 점수 관련 공지",body:"참여 +20점 · 후기 +10점 · 사진 +5점 · 밋업 개설 +30점 · 밋업 성사 +20점 · 친구 초대 +50점. 점수는 마이페이지와 명예의 전당에 반영돼요."},
{id:"level",title:"레벨업 안내",body:"Lv.1 물방울(0점) → Lv.2 윤슬(100점) → Lv.3 물결(300점) → Lv.4 너울(700점) → Lv.5 물보라(1500점) → Lv.6 파도(3000점)."},
{id:"badge",title:"배지 안내",body:"첫 만남, 첫 밋업 개설, 번개왕, 후기왕, 단골, 완주자, 추천왕, 윤슬 메이커, 파도 메이커, 시즌 배지가 있어요."},
{id:"meetup",title:"밋업 개설 관련 공지",body:"밋업 만들기 버튼을 누르면 새 밋업 작성 화면으로 바로 이동해요. 날짜, 시간, 장소, 모집 인원, 오픈카톡 링크를 입력하면 승인 대기로 등록됩니다."}
];return <main className="hero"><section className="heroCard"><p className="eyebrow">People Arrive, Discover, and Open up.</p><h1>오늘의 만남이,<br/>언젠가 오래 기억될<br/>추억이 되도록.</h1><p className="lead">파도는 사람을 연결하고, 함께한 순간을 기록하는 부산 2030 커뮤니티 플랫폼입니다.</p><div className="actions"><button className="btn primary" onClick={openCreate}>{approved?"📅 밋업 만들기":"파도 가입하기"}</button><button className="btn" onClick={openToday}>오늘의 밋업 보기</button></div></section>
<section className="noticeBox"><div className="sectionTitle"><div><p className="eyebrow">NOTICE</p><h2>공지사항</h2></div></div><div className="noticeGrid">{[...defaultNotices,...notices].slice(0,6).map(n=><article className="noticeCard" key={n.id}><b>📌 {n.title}</b><p>{n.body||n.content}</p></article>)}</div></section>
<section className="lightning"><p className="eyebrow">오늘의 번개</p><h2>⚡ {todayLightning?.title||"퇴근 후 저녁 먹으실 분?"}</h2><p className="meta">📍 {todayLightning?.location||"서면"} · 🕢 {todayLightning?.time||"오늘 19:30"}<br/>👥 현재 {(todayLightning?.participants||[]).length||0}명 참여 · 3명 모이면 정식 밋업 전환</p><button className="btn primary" onClick={()=>go("meetups")}>참여하기</button></section>
<section className="grid"><article className="card statBig"><span>👥 멤버</span><b>{members.filter(m=>m.status==="approved").length}명</b></article><article className="card statBig"><span>📅 이번 주 밋업</span><b>{week.length}개</b></article><article className="card statBig"><span>📸 후기</span><b>{reviews.length}개</b></article></section>
<section style={{marginTop:24}}><div className="sectionTitle"><h2>📅 이번 주 밋업</h2><button className="btn" onClick={()=>go("meetups")}>전체보기</button></div><div className="grid">{week.length?week.map(m=><article className="card" key={m.id}><h3>{m.title}</h3><p className="meta">{m.date} {m.time}<br/>📍 {m.location}<br/>신청 {(m.participants||[]).length}{m.max?` / ${m.max}`:""}명</p></article>):<article className="card">이번 주 공개된 밋업이 아직 없어요.</article>}</div></section></main>}
