import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./pado.css";
import Home from"./Home.jsx";
import Signup from"./Signup.jsx";
import Meetups from"./Meetups.jsx";
import Reviews from"./Reviews.jsx";
import Profile from"./Profile.jsx";
import Admin from"./Admin.jsx";
import HallOfFame from"./HallOfFame.jsx";
import{db,doc,getDoc}from"./firebase.js";
import{getSessionPhone,clearSessionPhone,isCrew,setCrew}from"./member.js";
function App(){const[route,setRoute]=useState(location.hash.replace("#","")||"home");const[member,setMember]=useState(null);const[crew,setCrewState]=useState(isCrew());useEffect(()=>{const f=()=>setRoute(location.hash.replace("#","")||"home");window.addEventListener("hashchange",f);return()=>window.removeEventListener("hashchange",f)},[]);async function reloadMember(){const phone=getSessionPhone();if(!phone){setMember(null);return}const s=await getDoc(doc(db,"members",phone));setMember(s.exists()?{id:s.id,...s.data()}:null)}useEffect(()=>{reloadMember()},[route]);const approved=member?.status==="approved";const go=n=>{location.hash=n};const logout=()=>{clearSessionPhone();setMember(null);alert("로그아웃 완료");go("home")};const crewLogin=()=>{if(crew){if(confirm("크루 모드를 종료할까요?")){setCrew(false);setCrewState(false)}return}const pw=prompt("크루 비밀번호를 입력해 주세요.");if(pw==="pado2026"){setCrew(true);setCrewState(true);alert("크루 모드 ON");go("admin")}else if(pw!==null)alert("비밀번호가 달라요.")};const ctx=useMemo(()=>({go,member,approved,crew,reloadMember,logout}),[member,approved,crew]);return <><header className="topbar"><button className="brand" onClick={()=>go("home")}>🌊 <b>파도</b></button><nav><button onClick={()=>go("meetups")}>밋업</button><button onClick={()=>go("reviews")}>후기</button><button onClick={()=>go("hall")}>명예의 전당</button><button onClick={()=>go("profile")}>마이페이지</button>{member?<button onClick={logout}>👤 {member.name}님</button>:<button onClick={()=>go("signup")}>파도 가입하기</button>}<button className="crewBtn" onClick={crewLogin}>크루</button></nav></header>{route==="home"&&<Home {...ctx}/>} {route==="signup"&&<Signup {...ctx}/>} {route==="meetups"&&<Meetups {...ctx}/>} {route==="reviews"&&<Reviews {...ctx}/>} {route==="profile"&&<Profile {...ctx}/>} {route==="admin"&&<Admin {...ctx}/>} {route==="hall"&&<HallOfFame {...ctx}/>}</>;}createRoot(document.getElementById("root")).render(<App/>);
