import { useEffect, useMemo, useState } from "react";
import { db, collection, addDoc, updateDoc, doc, onSnapshot, serverTimestamp, arrayUnion } from "./firebase.js";
import { getSessionPhone } from "./member.js";
const initial={title:"",date:"",time:"",location:"",host:"",min:3,max:"",cost:"",desc:"",kakao:"",isLightning:false};
const pad=n=>String(n).padStart(2,"0"); const fmtDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
export default function Meetups({ approved, member }) {
  const [meetups,setMeetups]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[view,setView]=useState("list"),[month,setMonth]=useState(new Date()),[selectedDate,setSelectedDate]=useState("");
  useEffect(()=>onSnapshot(collection(db,"meetups"),snap=>setMeetups(snap.docs.map(d=>({id:d.id,...d.data()})))),[]);
  const visible=meetups.filter(m=>m.status==="approved").sort((a,b)=>(a.date||"").localeCompare(b.date||""));
  const update=(k,v)=>setForm(p=>({...p,[k]:v})); const openCreate=(date="")=>{setForm({...initial,date});setOpen(true)};
  async function saveMeetup(){if(!approved){alert("승인된 파도 멤버만 밋업을 만들 수 있어요.");return} if(!form.title||!form.date||!form.location||!form.host){alert("밋업명, 날짜, 장소, 밋업장을 입력해 주세요.");return} await addDoc(collection(db,"meetups"),{...form,min:Number(form.min||3),max:form.max?Number(form.max):null,hostPhone:getSessionPhone(),participants:[],status:"pending",createdAt:serverTimestamp()});setForm(initial);setOpen(false);alert("🌊 밋업이 승인 대기로 등록됐어요.")}
  async function joinMeetup(m){if(!approved){alert("승인된 파도 멤버만 참가 신청할 수 있어요.");return}const phone=getSessionPhone();if((m.participants||[]).some(p=>p.phone===phone)){alert("이미 신청했어요.");return}await updateDoc(doc(db,"meetups",m.id),{participants:arrayUnion({phone,name:member?.name||"",checkedIn:false,joinedAt:Date.now()})});alert("🌊 이번 항해에 함께합니다.");if(m.kakao&&confirm("오픈채팅방으로 이동할까요?"))window.open(m.kakao,"_blank")}
  const days=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),startDay=first.getDay(),total=new Date(y,m+1,0).getDate(),arr=[];for(let i=0;i<startDay;i++)arr.push(null);for(let d=1;d<=total;d++)arr.push(new Date(y,m,d));return arr},[month]); const today=fmtDate(new Date());
  return <main className="page"><div className="sectionTitle"><div><p className="eyebrow">MEETUP</p><h1>다가오는 밋업</h1></div><button className="btn primary" onClick={()=>openCreate()}>📅 밋업 만들기</button></div><div className="tabs"><button className={view==="list"?"active":""} onClick={()=>setView("list")}>목록 보기</button><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}>캘린더 보기</button></div>
  {view==="list"?<section className="list">{visible.length?visible.map(m=><MeetupCard key={m.id} m={m} joinMeetup={joinMeetup}/>):<article className="item">아직 공개된 밋업이 없어요.</article>}</section>:<section><div className="calendarHead"><button className="btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h2>{month.getFullYear()}년 {month.getMonth()+1}월</h2><div><button className="btn" onClick={()=>setMonth(new Date())}>오늘</button> <button className="btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="calendarGrid">{["일","월","화","수","목","금","토"].map(w=><div className="weekday" key={w}>{w}</div>)}{days.map((d,i)=>{const date=d?fmtDate(d):"";const events=visible.filter(m=>m.date===date);return <div key={i} className={`dayCell ${date===today?"today":""}`}>{d&&<><div className="dayNumber">{d.getDate()}</div>{events.map(e=><button className="eventChip" key={e.id} onClick={()=>setSelectedDate(date)}>{e.title}</button>)}{!events.length&&<button className="emptyCreate" onClick={()=>openCreate(date)}>+ 이 날 밋업 만들기</button>}</>}</div>})}</div>{selectedDate&&<section className="card" style={{marginTop:16}}><h3>{selectedDate} 밋업</h3>{visible.filter(m=>m.date===selectedDate).map(m=><MeetupCard key={m.id} m={m} joinMeetup={joinMeetup}/>)}{!visible.some(m=>m.date===selectedDate)&&<p className="muted">이 날은 아직 밋업이 없어요.</p>}</section>}</section>}
  <div className={`modal ${open?"open":""}`}><div className="sheet"><h2>새 밋업 만들기</h2><p className="muted">People Arrive, Discover, and Open up.<br/>만나고, 발견하고, 마음을 열다.</p><label>밋업명</label><input value={form.title} onChange={e=>update("title",e.target.value)} placeholder="예) 퇴근 후 저녁 먹으실 분?"/><div className="row"><div><label>날짜</label><input type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></div><div><label>시간</label><input type="time" value={form.time} onChange={e=>update("time",e.target.value)}/></div></div><label>장소</label><input value={form.location} onChange={e=>update("location",e.target.value)} placeholder="예) 모모스커피 영도 로스터리"/><label>밋업장</label><input value={form.host} onChange={e=>update("host",e.target.value)} placeholder="예) 김세경"/><div className="row"><div><label>최소 인원</label><input type="number" value={form.min} onChange={e=>update("min",e.target.value)}/></div><div><label>최대 인원</label><input type="number" value={form.max} onChange={e=>update("max",e.target.value)} placeholder="비워두면 제한 없음"/></div></div><label>예상 비용</label><input value={form.cost} onChange={e=>update("cost",e.target.value)} placeholder="예) 무료 · 각자 계산 · 1/N"/><label><input type="checkbox" checked={form.isLightning} onChange={e=>update("isLightning",e.target.checked)} style={{width:"auto",marginRight:8}}/>오늘의 번개로 표시</label><label>밋업 소개</label><textarea value={form.desc} onChange={e=>update("desc",e.target.value)} placeholder="오늘은 어떤 시간을 함께 보내고 싶나요?"/><label>오픈채팅 링크</label><input value={form.kakao} onChange={e=>update("kakao",e.target.value)} placeholder="참가 신청 후 이동할 오픈채팅 링크"/><div className="actions right"><button className="btn" onClick={()=>setOpen(false)}>취소</button><button className="btn primary" onClick={saveMeetup}>📅 밋업 만들기</button></div></div></div></main>;}
function MeetupCard({m,joinMeetup}){return <article className="item"><span className={`pill ${m.isLightning?"orange":"approved"}`}>{m.isLightning?"오늘의 번개":"공개"}</span><h3>{m.title}</h3><p className="meta">{m.date} {m.time}<br/><a href={`https://map.naver.com/p/search/${encodeURIComponent(m.location||"")}`} target="_blank">📍 {m.location}</a><br/>밋업장: {m.host} · 신청 {(m.participants||[]).length}{m.max?` / ${m.max}`:""}명</p>{m.desc&&<p>{m.desc}</p>}<button className="btn primary" onClick={()=>joinMeetup(m)}>참가 신청</button></article>}